name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # 安定性のた3.11を推奨しますが、3.13でも動作可能です

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: >
        pyinstaller 
        --onefile 
        --noconsole 
        --name "SteelStrengthCalculationMiya-v1.1.0" 
        --collect-all streamlit 
        --add-data "readme.md;." 
        --copy-metadata streamlit 
        app.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SteelStrengthCalculationMiya-v1.1.0
        path: dist/SteelStrengthCalculationMiya-v1.1.0.exe